Add CI for example

diff --git a/.github/workflows/futs.yml b/.github/workflows/futs.yml
--- a/.github/workflows/futs.yml
+++ b/.github/workflows/futs.yml
@@ -39,6 +39,16 @@ jobs:
                 echo "Unit Tests failed"
                 exit 1
              fi
+      - name: Run Example Tests
+        run: |
+             ./build/examples/demo_project/DEMO_PROJ_Tests
+             if [ $? -eq 1 ]; then
+                echo "Unit Tests failed as expected"
+                exit 0
+             else
+                echo "Unit Tests that should fail passed"
+                exit 1
+             fi
       - name: Get Coverage Data
         continue-on-error: true
         run: |
