Updated Mac build

diff --git a/.github/workflows/futs_mac.yml b/.github/workflows/futs_mac.yml
--- a/.github/workflows/futs_mac.yml
+++ b/.github/workflows/futs_mac.yml
@@ -17,4 +17,11 @@ jobs:
             cmake --build build
       - name: Run Tests
         run: |
-            for i in $(ls build/bin/*); do ./$i; done
+             ./build/FortUTF_Tests
+             if [ $? -neq 0]; then
+                echo "Unit Tests completed succesfully"
+                exit 0
+             else
+                echo "Unit Tests failed"
+                exit 1
+             fi
