Added more tests and improved CI

diff --git a/.github/workflows/futs.yml b/.github/workflows/futs.yml
--- a/.github/workflows/futs.yml
+++ b/.github/workflows/futs.yml
@@ -13,7 +13,16 @@ jobs:
             cmake -H. -Bbuild -DBUILD_TESTS=ON
             cmake --build build
       - name: Run Tests
-        run: ./build/FortUTF_Tests
+        run: |
+             ./build/FortUTF_Tests
+             if [ $? -neq 0]; then
+                echo "Unit Tests completed succesfully"
+                exit 0
+             else
+                echo "Unit Tests failed"
+                exit 1
+             fi
+                
 
   build_example:
     name: Ubuntu Latest Example
@@ -22,8 +31,15 @@ jobs:
       - uses: actions/checkout@v2
       - name: Build Example Project
         run: |
-            cd examples/demo_project
-            cmake -H. -Bbuild
-            cmake --build build
-            ./build/DEMO_PROJ_Tests
+             cd examples/demo_project
+             cmake -H. -Bbuild
+             cmake --build build
+             ./build/DEMO_PROJ_Tests
+             if [ $? -neq 0]; then
+                echo "Unit Tests completed succesfully"
+                exit 0
+             else
+                echo "Unit Tests failed"
+                exit 1
+             fi
 
